// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  formWrap: string
  input: string
  inputWrap: string
  label: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
